version: '3'

services:
  mysql-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=RootPassword123
      - MYSQL_DATABASE=r-place
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=Password123
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/init.sql
  node-app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "4000:4000"
    command: sh -c "npm install && npm start"
    depends_on:
      - mysql-db
    environment:
      - MYSQL_HOST=mysql-db
